// src/routes/(app)/(auth)/login/+page.svelte
<script lang="ts">
  import { page } from "$app/stores";
  import { trpc } from "$lib/trpc/client";
  import { goto } from "$app/navigation";
  import { decryptWithPassword } from "$lib/utils/encryption";
  import Head from "$lib/ui/Head.svelte";
  import Link from "$lib/ui/Link.svelte";
  import Label from "$lib/ui/Label.svelte";
  import Input from "$lib/ui/Input.svelte";
  import PasswordInput from "$lib/ui/PasswordInput.svelte";
  import Button from "$lib/ui/Button.svelte";
  import FormError from "$lib/ui/FormError.svelte";

  let email = "";
  let password = "";

  const login = trpc.auth.login.createMutation({
    onSuccess: async (encryptedSecret) => {
      // Decrypt secret with password
      const privateKey = await decryptWithPassword(encryptedSecret, password);

      // Store private key locally
      localStorage.setItem("sk", privateKey);

      // Delete every derived key from other sessions
      for (const key in localStorage) {
        if (key.startsWith("dk_")) {
          localStorage.removeItem(key);
        }
      }

      const redirectTo = decodeURIComponent(
        $page.url.searchParams.get("redirectTo") || "/",
      );

      goto(redirectTo);
    },
  });

  async function handleLogin() {
    $login.mutate({ email, password });
  }

  $: validationErrors = $login.error?.data?.validationErrors;
  $: error = $login.error?.data?.error;
</script>

<Head
  title="Login | Boble Web Chat"
  description="Login to your account and start chatting with your friends."
/>

<h1 class="pb-3 text-xl font-bold">Login to your account</h1>
<p class="text-sm text-zinc-500">
  Need an account?{" "}
  <Link href="/create-account">Sign up.</Link>
</p>

<form on:submit|preventDefault={handleLogin} class="flex flex-col gap-3 pt-8">
  <Label for="email">
    Email
    <Input
      bind:value={email}
      name="email"
      type="email"
      autocomplete="email"
      errors={validationErrors?.email}
    />
  </Label>
  <Label for="password">
    Password
    <PasswordInput
      bind:value={password}
      name="password"
      autocomplete="current-password"
      errors={validationErrors?.password}
    />
  </Label>

  <div
    class="flex justify-between items-center text-xs font-medium text-zinc-500"
  >
    <div class="flex gap-1.5 items-center">
      <input
        type="checkbox"
        id="remember"
        name="remember"
        class="mb-0.5"
        checked
      />
      <label for="remember">Remember me</label>
    </div>
    <Link href="/forgot-password" class="text-xs">Forgot password?</Link>
  </div>

  <Button isLoading={$login.isPending} type="submit" fullWidth>Login</Button>

  {#if error}
    <FormError message={error} />
  {/if}
</form>

// src/routes/login.tsx
import { signIn } from "@auth/solid-start/client";
import { Title } from "solid-start";
import { createServerData$, redirect } from "solid-start/server";
import { getServerSession } from "~/auth/auth";
import { Header } from "~/components/Header";
import { Label, Input, PasswordInput } from "~/components/Form";
import { Link } from "~/components/Link";
import type { JSX } from "solid-js";
import type { OAuthProviderType } from "@auth/core/providers";

export function routeData() {
  return createServerData$(
    async (_, event) => {
      const session = await getServerSession(event.request);
      const redirectTo = new URL(event.request.url).searchParams.get("redirectTo");

      if (session) throw redirect(redirectTo || '/');
    },
  );
};

export default function LoginPage() {
  return (
    <>
      <Header loggedOut />
      <Title>Login | BOBLE Web Chat</Title>
      <main class="flex flex-col gap-14 justify-center items-center pt-20 lg:flex-row lg:gap-10 lg:items-start">
        <section class="flex flex-col justify-center p-6 w-full max-w-md bg-white rounded-md border shadow-md">
          <h1 class="pb-3 text-xl font-bold">Login to your account</h1>
          <p class="text-sm text-zinc-500">
            Need an account?{" "}
            <Link href="/signup">Sign up.</Link>
          </p>

          <div class="flex flex-col gap-3 pt-8">
            <Label for="email">Email
              <Input id="email" name="email" type="email" />
            </Label>
            <Label for="password">Password
              <PasswordInput id="password" name="password" />
            </Label>

            <div class="flex justify-between items-center text-xs font-medium text-zinc-500">
              <div class="flex gap-1.5 items-center">
                <input type="checkbox" checked id="remember" name="remember" class="mb-0.5" />
                <label for="remember">
                  Remember me
                </label>
              </div>
              <Link href="/forgot-password">Forgot password?</Link>
            </div>

            <button type="submit" class="p-2 w-full text-sm font-bold text-white bg-cyan-700 rounded-md shadow-sm transition hover:brightness-110 focus:outline-cyan-600">
              Login
            </button>
          </div>

          <span class="relative my-8 h-px bg-zinc-200">
            <span class="absolute top-1/2 left-1/2 px-1 text-sm bg-white -translate-x-1/2 -translate-y-1/2 text-zinc-500">or</span>
          </span>

          <div class="flex flex-col gap-2">
            <SocialProviderButton provider="google" class="border">
              Continue with Google
            </SocialProviderButton>
            <SocialProviderButton provider="github" class="text-white bg-black">
              Continue with GitHub
            </SocialProviderButton>
          </div>
        </section>
        <section class="flex gap-3 w-full max-w-md lg:pt-6">
          <img
            src="/boble.svg"
            alt="BOBLE logo"
            class="w-12 h-12"
          />
          <div>
            <h1 class="text-lg font-bold">
              <span class="tracking-wide">BOBLE </span>
              Web Chat
            </h1>
            <p class="pt-1 text-sm">
              Chat with your friends and family from any device.
            </p>
          </div>
        </section>
      </main>
    </>
  );
}

function SocialProviderButton(props: JSX.ButtonHTMLAttributes<HTMLButtonElement> & { provider: OAuthProviderType }) {
  return (
    <button
      onClick={() => signIn(props.provider)}
      {...props}
      class={`flex items-center justify-center gap-2.5 p-2 w-full rounded-md shadow-sm focus:outline-cyan-600 text-sm font-medium ${props.class}`}
    >
      <img
        src={`/icons/${props.provider}.svg`}
        alt={props.provider}
        class="w-4 h-4"
      />
      {props.children}
    </button>
  );
}
