// app/src/components/SendMessage.tsx
import { createSignal, Show } from "solid-js";
import { sendMessage } from "~/utils/chat";


export function SendMessage() {
  const [text, setText] = createSignal("");

  function handleSubmit(e: Event) {
    e.preventDefault();
    if (!text()) return;

    sendMessage(text());
    setText("");
  }

  return (
    <form
      onSubmit={handleSubmit}
      class="flex gap-2 p-2 border-t bg-zinc-50"
    >
      <label for="message" class="sr-only">Message</label>
      <div class="relative flex-1">
        <input
          id="message"
          name="message"
          type="text"
          value={text()}
          onInput={(e) => setText(e.target.value)}
          placeholder="Type a message..."
          class="block py-1.5 pr-12 pl-2 w-full rounded-md border shadow-sm placeholder:text-zinc-400 focus:outline-cyan-600"
          autocomplete="off"
        />
        <Show when={text()}>
          <button
            type="submit"
            aria-label="Send message"
            class="absolute right-0 top-1/2 py-1 px-2 rounded-md -translate-y-1/2 focus:outline-cyan-600"
          >
            <img src="/icons/send.svg" alt="Send message" class="w-6 h-6" />
          </button>
        </Show>
      </div>
    </form>);
}

// src/routes/(app)/chat/[chatId]/_components/SendMessage.svelte
<script lang="ts">
  import { enhance } from "$app/forms";
  import { replyingTo } from "./stores";
  import Attachments from "./Attachments/Attachments.svelte";
  import Moods from "./Moods/Moods.svelte";

  let text = "";

  let textInput: HTMLInputElement | undefined = undefined;

  $: if ($replyingTo) textInput?.focus();
</script>

<div class="flex gap-1.5 items-center sm:gap-2.5">
  <Moods />
  <Attachments />

  <form
    action="?/sendTextMessage"
    method="post"
    use:enhance={() => {
      return async ({ update }) => {
        await update();
        $replyingTo = null;
      };
    }}
    class="flex flex-1 gap-2.5 items-center"
  >
    <input type="hidden" name="replyToId" value={$replyingTo?.id ?? null} />

    <label for="message" class="sr-only">Message</label>
    <input
      bind:value={text}
      bind:this={textInput}
      id="message"
      name="message"
      type="text"
      placeholder="Type a message"
      class="block py-1.5 px-2 ml-1 w-full rounded-md border shadow-sm placeholder:text-zinc-400 focus:outline-cyan-600"
      autocomplete="off"
    />
    {#if text.length}
      <button
        type="submit"
        title="Send message"
        aria-label="Send message"
        class="p-0.5 rounded-md min-w-fit focus:outline-cyan-600"
      >
        <img src="/icons/send.svg" alt="Send message" class="w-7 h-7" />
      </button>
    {:else}
      <button
        type="button"
        title="Record audio"
        aria-label="Record audio"
        class="p-0.5 rounded-md min-w-fit focus:outline-cyan-600"
      >
        <img src="/icons/microphone.svg" alt="Record audio" class="h-7" />
      </button>
    {/if}
  </form>
</div>
