// src/components/Message.tsx
import { Show } from "solid-js";
import type { Message } from "~/db/getMessages";

type MessageProps = {
  message: Message,
  prevMessage: Message
  isOwn: boolean,
}

export function Message(props: MessageProps) {
  const prevDate = new Date(props.prevMessage?.createdAt!);
  const currentDate = new Date(props.message.createdAt!);
  const firstOfDate = prevDate.getDate() !== currentDate.getDate();
  const isFirst = props.prevMessage?.senderId !== props.message.senderId || firstOfDate;

  return (
    <>
      <Show when={firstOfDate}>
        <DateIndicator date={props.message.createdAt!} />
      </Show>
      <li
        class={`relative flex items-end gap-x-2 pt-1.5 pb-1 pl-2.5 pr-1 bg-cyan-700 rounded-md shadow-sm 
      ${props.isOwn ? "self-end bg-cyan-700 text-white" : "self-start bg-white"}
      ${isFirst ? props.isOwn ? "rounded-tr-none" : "rounded-tl-none" : ""}
      ${isFirst ? "mt-2" : "mt-1"}`}
      >
        <p class="w-full">{props.message.text}</p>
        <p class="leading-3 text-right text-[10px]">
          {formatMessageTime(props.message.createdAt!)}
        </p>

        <Show when={isFirst}>
          <span
            class={`absolute top-0 w-0 h-0 border-transparent border-t-[10px]
          ${props.isOwn ? "border-t-cyan-700 border-r-[5px] -right-1" : "border-t-white border-l-[5px] -left-1"}`}
          />
        </Show>
      </li>
    </>
  );
}

function formatMessageTime(date: Date) {
  return new Date(date).toLocaleTimeString("es-ES", {
    hour: "numeric",
    minute: "numeric",
  });
}

function DateIndicator(props: { date: Date }) {
  return (
    <span class="bg-white rounded-md shadow-sm text-xs px-1.5 py-1 mx-auto mt-2">
      {formatDate(new Date(props.date))}
    </span>
  );
}

function formatDate(date: Date) {
  const today = new Date();

  if (date.getFullYear() !== today.getFullYear() ||
    date.getMonth() !== today.getMonth()) {
    return date.toLocaleDateString("es-ES", {
      day: "numeric",
      month: "numeric",
      year: "numeric",
    });
  }

  if (today.getDate() - date.getDate() > 6) {
    return date.toLocaleDateString("es-ES", {
      day: "numeric",
      month: "numeric",
      year: "numeric",
    });
  }

  if (today.getDate() === date.getDate()) {
    return "Today";
  }

  if (today.getDate() - date.getDate() === 1) {
    return "Yesterday";
  }

  return date.toLocaleDateString("es-ES", {
    weekday: "long",
  });
}

// src/routes/(app)/chat/[chatId]/_components/Message/Message.svelte
<script lang="ts">
  import { formatDate } from "$lib/utils/date";
  import { isValidUrl } from "$lib/utils/url";
  import { longPress } from "$lib/actions/longPress";
  import type { Message } from "$lib/db/message/getMessages";
  import TextMessage from "./TextMessage.svelte";
  import ImageMessage from "./ImageMessage.svelte";
  import GifMessage from "./GifMessage.svelte";
  import LinkMessage from "./LinkMessage.svelte";
  import MessageActions from "./MessageActions.svelte";

  export let message: Message;
  export let prevMessage: Message;
  export let lastReadAt: Date;
  export let isOwn: boolean;

  const prevDate = new Date(prevMessage?.createdAt!);
  const currentDate = new Date(message.createdAt!);
  const firstOfDate = prevDate.getDate() !== currentDate.getDate();
  const isFirst = prevMessage?.senderId !== message.senderId || firstOfDate;
  const createdAt = new Date(message.createdAt!);

  let actionsOpen = false;
</script>

{#if firstOfDate && message.createdAt}
  <span
    class="sticky top-3 z-10 py-1 mx-auto mt-3 w-20 text-xs text-center bg-white rounded-md shadow-sm"
  >
    {formatDate(createdAt)}
  </span>
{/if}
<li
  class={`relative rounded-md shadow-sm sm:max-w-[80%] md:max-w-full lg:max-w-[80%] 
      ${isOwn ? "self-end bg-cyan-700 text-white" : "self-start bg-white"}
      ${isFirst ? (isOwn ? "rounded-tr-none" : "rounded-tl-none") : ""}
      ${isFirst ? "mt-3" : "mt-1"}`}
>
  <button
    on:contextmenu|preventDefault={() => (actionsOpen = true)}
    use:longPress={() => (actionsOpen = true)}
    class="block text-left"
  >
    {#if message.type === "image"}
      <ImageMessage {message} {lastReadAt} {isOwn} />
    {:else if message.type === "gif"}
      <GifMessage {message} {lastReadAt} {isOwn} />
    {:else if isValidUrl(message.text ?? "")}
      <LinkMessage {message} {lastReadAt} {isOwn} />
    {:else}
      <TextMessage {message} {lastReadAt} {isOwn} />
    {/if}
    {#if isFirst}
      <span
        class={`absolute top-0 w-0 h-0 border-transparent border-t-[10px]
        ${
          isOwn
            ? "border-t-cyan-700 border-r-[5px] -right-1"
            : "border-t-white border-l-[5px] -left-1"
        }
      `}
      />
    {/if}
  </button>

  {#if actionsOpen}
    <MessageActions bind:isOpen={actionsOpen} {message} {isOwn} />
  {/if}
</li>
