// src/routes/(app)/chat/_components/ChatList.svelte
<script lang="ts">
	import { page } from '$app/stores';
	import FilterChats from './FilterChats.svelte';
	import Chat from './Chat.svelte';
	import type { Chats } from '$lib/db/getChats';

	export let chats: Chats;

	let filteredChats = chats;
</script>

<section>
	<FilterChats initialChats={chats} bind:filteredChats={filteredChats} />
	{#if filteredChats.length > 0}
		<ul class="border-t">
			{#each filteredChats as chat}
				<Chat {chat} isSelected={chat.id === $page.params.chatId} />
			{/each}
		</ul>
	{:else}
		<p class="py-1 pl-3 font-medium border-t">No chats found.</p>
	{/if}
</section>

// src/components/ChatList.tsx
import { For, createSignal } from "solid-js";
import { useParams } from "@solidjs/router";
import { FilterChats } from "./FilterChats";
import { Chat } from "./Chat";
import type { Chats } from "~/db/getChats";

export function ChatList(props: { chats: Chats }) {
  const params = useParams<{ chatId: string }>();
  const [filteredChats, setFilteredChats] = createSignal<Chats>(props.chats);

  return (
    <section class="w-full max-w-sm bg-zinc-50">
      <FilterChats initialChats={props.chats} setChats={setFilteredChats} />
      <ul class="border-t">
        <For each={filteredChats()}>
          {(chat) => <Chat chat={chat} isSelected={chat.id === params.chatId} />}
        </For>
      </ul>
    </section>
  );
}
