// src/routes/(app)/chat/[chatId]/_components/MessageList.svelte
<script lang="ts">
	import { onDestroy } from 'svelte';
	import { joinChat, subscribeToMessages, unsubscribeFromMessages } from '$lib/utils/chat';
	import Message from './Message.svelte';
	import type { Messages } from '$lib/db/getMessages';

	export let initialMessages: Messages;
	export let lastReadAt: Date;
	export let chatId: string;
	export let userId: string;

	let messages = initialMessages;
	let messageList: HTMLElement | undefined = undefined;

	$: {
		joinChat(chatId);
		messages = initialMessages;
	}

	subscribeToMessages((message) => {
		messages = [...messages, message];
		if (!messageList) return;
		messageList.scrollTo({ top: messageList.scrollHeight, behavior: 'smooth' });
	});

	onDestroy(() => unsubscribeFromMessages());
</script>

<section bind:this={messageList} class="overflow-y-auto px-4 h-full bg-zinc-100">
	{#if messages.length === 0}
		<div class="pt-10 text-center">
			<p class="mb-4 text-lg font-bold">No messages yet</p>
			<p>Start the conversation to see your messages here.</p>
		</div>
	{:else}
		<ul class="flex flex-col py-2 h-full text-sm">
			{#each messages as message, i}
				<Message
					{message}
					prevMessage={messages[i - 1]}
					{lastReadAt}
					isOwn={message.senderId === userId}
				/>
			{/each}
		</ul>
	{/if}
</section>

// src/components/MessageList.jsx
import { Show, For } from "solid-js";
import { useMessages } from "~/utils/chat";
export function MessageList() {
    const messages = useMessages();
    return (<section class="flex-grow px-4 pt-5 bg-zinc-100">
      <Show when={messages().length === 0}>
        <div class="pt-5 text-center">
          <p class="mb-4 text-lg font-bold">No messages yet.</p>
          <p>Start the conversation to see your messages here.</p>
        </div>
      </Show>
      <ul class="flex flex-col gap-4">
        <For each={messages()}>
          {(message) => (<li class="self-start py-1 px-2.5 bg-white rounded-md border shadow-sm">
              {message}
            </li>)}
        </For>
      </ul>
    </section>);
}
