// src/components/MessageList.tsx
import { Show, For, createEffect, createSignal, onCleanup } from "solid-js";
import { joinChat, subscribeToMessages, unsubscribeFromMessages } from "~/utils/chat";
import { Message } from "./Message";
import type { Messages } from "~/db/getMessages";

type MessageListProps = {
  initialMessages: Messages,
  lastReadAt: Date,
  chatId: string
  userId: string
}

export function MessageList(props: MessageListProps) {
  const [messages, setMessages] = createSignal(props.initialMessages);
  let messageList: HTMLUListElement | undefined = undefined;

  createEffect(() => {
    joinChat(props.chatId);
    setMessages(props.initialMessages);
  });

  subscribeToMessages((message) => {
    setMessages((messages) => [...messages, message]);
    if (!messageList) return;
    messageList.scrollTo({ top: messageList.scrollHeight, behavior: "smooth" });
  });

  onCleanup(() => unsubscribeFromMessages());

  return (
    <section ref={messageList} class="overflow-y-auto py-2 px-4 h-full bg-zinc-100">
      <Show when={messages().length === 0}>
        <div class="pt-5 text-center">
          <p class="mb-4 text-lg font-bold">No messages yet.</p>
          <p>Start the conversation to see your messages here.</p>
        </div>
      </Show>
      <ul class="flex flex-col h-full text-sm">
        <For each={messages()}>
          {(message, i) => (
            <Message
              message={message}
              prevMessage={messages()[i() - 1]}
              lastReadAt={props.lastReadAt}
              isOwn={message.senderId === props.userId}
            />
          )}
        </For>
      </ul>
    </section>
  );
}

// src/routes/(app)/k/[chatId]/_components/MessageList.svelte
<script lang="ts">
  import { onDestroy, tick } from "svelte";
  import {
    onDeleteMessage,
    onMessage,
    unsubscribeFromMessages,
  } from "$lib/socket/client";
  import { decryptMessage } from "$lib/utils/encryption";
  import { chats } from "$lib/stores/chats";
  import { messages } from "$lib/stores/store";
  import type { Messages } from "$lib/db/message/getMessages";
  import Message from "./Message/Message.svelte";
  import EncryptionPrompt from "./EncryptionPrompt.svelte";
  import AddContactPrompt from "./AddContactPrompt.svelte";
  import ScrollBottom from "./ScrollBottom.svelte";

  export let initialMessages: Messages;
  export let lastReadAt: Date;
  export let chatId: string;
  export let userId: string;
  export let isSavedContact: boolean;

  $: chat = $chats.find((chat) => chat.id === chatId);

  let messageContainer: HTMLElement;
  let showScrollBottom = false;

  // Change messages on chat change
  $: if (chatId) {
    messages.set(initialMessages);
  }

  // Scroll bottom instantly on chat change
  $: if (chatId) {
    tick().then(() => {
      messageContainer?.scrollTo({
        top: messageContainer.scrollHeight,
        behavior: "instant",
      });
    });
  }

  function scrollBottom() {
    messageContainer?.scrollTo({
      top: messageContainer.scrollHeight,
      behavior: "smooth",
    });
  }

  function isNearEnoughToBottom(distance: number) {
    return (
      messageContainer.scrollTop + messageContainer.clientHeight >=
      messageContainer.scrollHeight - distance
    );
  }

  function handleScroll() {
    if (isNearEnoughToBottom(10)) {
      showScrollBottom = false;
      chats.readChat(chatId);
      return;
    }
    showScrollBottom = true;

    // Close message actions context menu
    messageContainer.click();
  }

  onMessage(async (message) => {
    if (message.chatId !== chatId) return;

    const decryptedMessage = await decryptMessage(message, chatId);

    $messages = [...$messages, decryptedMessage];
    await tick();

    // Scroll bottom if message is own or user is near bottom
    if (message.senderId === userId || isNearEnoughToBottom(300)) {
      scrollBottom();
    }
  });

  onDeleteMessage((messageId, chatId2) => {
    if (chatId !== chatId2) return;

    $messages = $messages.filter((message) => message.id !== messageId);
  });

  onDestroy(() => unsubscribeFromMessages());
</script>

<section
  on:scroll={handleScroll}
  bind:this={messageContainer}
  class="overflow-y-scroll px-4 h-full flex flex-col bg-stone-100 bg-repeat
  bg-[url('/pattern.png')] scroll-smooth"
>
  <EncryptionPrompt />

  {#if $messages.length === 0}
    <div class="my-auto text-center">
      <p class="mb-4 text-lg font-bold">No messages yet</p>
      <p>Start the conversation to see your messages here.</p>
    </div>
  {:else}
    <ul class="flex flex-col pb-4 text-sm">
      {#each $messages as message, i (message.id)}
        <Message
          {message}
          prevMessage={$messages[i - 1]}
          {lastReadAt}
          isOwn={message.senderId === userId}
        />
      {/each}
    </ul>
  {/if}

  {#if !isSavedContact}
    <AddContactPrompt />
  {/if}

  {#if showScrollBottom}
    <ScrollBottom
      onScrollBottom={scrollBottom}
      unreadCount={chat?.unreadCount ?? 0}
    />
  {/if}
</section>
